export const english_word = ["time", "man", "say", "but", "quite", "look", "list", "call",
    "or", "live", "father", "food", "something", "people", "as", "word", "miss", "night", "few",
    "write", "so", "learn", "quickly", "story", "young", "spell", "found", "hear", "school",
    "and", "on", "along", "put", "own", "same", "water", "this", "never", "four", "had", "she",
    "on", "paper", "set", "next", "from", "kind", "little", "men", "below", "now", "long", "move",
    "each", "it", "her", "study", "little", "came", "near", "being", "great", "you", "tell",
    "four", "he", "leave", "big", "each", "when", "carry", "those", "boy", "these", "should",
    "talk", "start", "tree", "for", "mean", "stop", "from", "sound", "hard", "girl", "take",
    "know", "mountain", "make", "water", "until", "thing", "air", "which", "it's", "of", "don't",
    "went", "watch", "had", "we", "ask", "three", "try", "end", "about", "be", "over", "song", "far",
    "his", "soon", "letter", "help", "such", "work", "white", "own", "left", "eye", "first", "as",
    "tell", "it", "she", "saw", "was", "far", "with", "then", "great", "her", "are", "be", "children",
    "water", "said", "move", "without", "why", "mother", "face", "second", "head", "live", "right",
    "long", "after", "high", "keep", "turn", "leave", "group", "also", "all", "most", "thought", "came",
    "your", "its", "another", "each", "country", "up", "took", "tree", "name", "about", "spell", "change",
    "add", "don't", "idea", "group", "has", "she", "or", "call", "must", "America", "book", "the", "until",
    "always", "us", "sometimes", "line", "children", "not", "together", "above", "come", "head", "sentence",
    "light", "its", "look", "above", "before", "said", "found", "miss", "car", "feet", "young", "these",
    "help", "need", "come", "always", "sometimes", "don't", "being", "close", "hand", "down", "if", "which",
    "find", "an", "america", "book", "too", "walk", "food", "can", "stop", "under", "many", "this", "at",
    "for", "eat", "soon", "really", "also", "want", "up", "city", "does", "while", "but", "just", "follow",
    "place", "him", "near", "spell", "city", "only", "more", "way", "story", "letter", "come", "got", "down",
    "place", "over", "too", "good", "great", "did", "work", "of", "what", "man", "another", "light", "watch",
    "car", "important", "seem", "think", "of", "under", "when", "family", "later", "eat", "get", "still",
    "animal", "state", "tree", "know", "thought", "were", "last", "large", "other", "away", "read", "between",
    "both", "about", "quite", "really", "were", "hand", "left", "question", "after", "list", "oil", "also",
    "name", "idea", "plant", "use", "people", "mean", "need", "would", "different", "begin", "hear", "add",
    "mile", "sound", "hard", "line", "air", "we", "does", "good", "different", "learn", "side", "would",
    "number", "far", "every", "took", "turn", "from", "above", "old", "hear", "was", "even", "back", "letter",
    "father", "why", "important", "take", "we", "world", "day", "work", "very", "make", "me", "like", "miss",
    "very", "quickly", "open", "away", "came", "white", "eye", "by", "than", "kind", "life", "old", "walk",
    "name", "new", "it's", "say", "turn", "learn", "play", "often", "what", "might", "plant",
].map(item => {
    return {"word": item, "status":"", "answer":"" }
 })

export const turkish_word = ["zor", "anne", "hiç", "yapmak", "sistem", "başlamak", "bunu", "başka", "anlatmak",
    "ev", "hem", "hal", "veya", "bırakmak", "hal", "kişi", "yemek", "yol", "düşünmek", "bulunmak", "dış",
    "ki", "hep", "ne", "gibi", "şimdi", "tek", "söz", "şu", "ay", "getirmek", "girmek", "ne", "bir", "olay",
    "son", "arkadaş", "çıkmak", "geçmek", "burada", "diğer", "şu", "nasıl", "dış", "almak", "göz", "getirmek",
    "şu", "tüm", "sevmek", "tüm", "bugün", "kullanılmak", "saat", "bulunmak", "görmek", "diye", "aynı",
    "söylemek", "doğru", "karşı", "kalmak", "sadece", "almak", "yüzde", "aynı", "devlet", "küçük", "bütün",
    "gelmek", "ise", "ben", "kadar", "sonuç", "bunlar", "görmek", "daha", "ya", "ses", "alt", "şimdi",
    "ile", "küçük", "çok", "yaşamak", "onlar", "kullanmak", "yaş", "yıl", "göre", "hiçbir", "gibi",
    "istemek", "ad", "sağlamak", "yüzde", "aynı", "sadece", "bunun", "göstermek", "şey", "sevmek", "para",
    "her", "ülke", "sevmek", "açmak", "çünkü", "sadece", "en", "hayat", "gerekmek", "zaman", "yine", "sıra",
    "demek", "kim", "dünya", "ürün", "göstermek", "sahip", "yaş", "böyle", "onun", "biri", "durmak",
    "sonuç", "çıkarmak", "vermek", "birbiri", "doğru", "iş", "bunun", "ki", "biri", "dönmek", "konu",
    "yapılmak", "çekmek", "önemli", "öyle", "diğer", "gelmek", "göstermek", "o", "onlar", "üzerinde",
    "yer", "devlet", "çalışmak", "verilmek", "hiçbir", "ama", "yine", "konu", "sen", "üzerinde", "geçmek",
    "taraf", "duymak", "ve", "bunu", "şekil", "diğer", "kullanılmak", "çünkü", "en", "hayat", "son",
    "devlet", "yeni", "baş", "baba", "arkadaş", "kitap", "bazı", "gitmek", "üzerinde", "yok", "gibi",
    "alt", "tek", "yüz", "göz", "tüm", "tutmak", "dış", "neden", "sonra", "çok", "biri", "sıra",
    "bulunmak", "alan", "girmek", "ise", "ve", "koymak", "görmek", "söylemek", "saat", "demek", "değil",
    "yok", "kadın", "olmak", "anlamak", "su", "anlatmak", "getirmek", "biz", "çalışmak", "girmek", "atmak",
    "öyle", "bu", "nasıl", "o", "daha", "hemen", "hep", "şey", "ülke", "oturmak", "ev", "sorun", "şekil",
    "el", "dönmek", "iyi", "diye", "kişi", "iki", "iki", "ara", "arkadaş", "alınmak", "el", "değil",
    "bakmak", "dış", "bir", "hemen", "düşünmek", "güzel", "söylemek", "yine", "anlamak", "kitap",
    "çekmek", "yol", "alt", "kişi", "kapı", "ne", "sağlamak", "kız", "yemek", "sorun", "bunlar", "dünya",
    "sonra", "girmek", "yani", "çıkmak", "son", "yine", "çıkarmak", "anne", "güzel", "yer", "açmak",
    "iyi", "geçmek", "genç", "el", "gerekmek", "çalışmak", "içinde", "bile", "an", "yok", "biraz",
    "şekil", "atmak", "süre", "dünya", "yaşamak", "ürün", "su", "etmek", "işte", "çocuk", "hiçbir",
    "hem", "karşı", "söz", "bırakmak", "ancak", "sağlamak", "bırakmak", "başka", "kitap", "düşmek",
    "ilk", "diye", "artık", "devlet", "yani", "konuşmak", "içinde", "ise", "tek", "yıl", "olmak",
    "uzun", "ama", "yazmak", "sağlamak", "bakmak", "söz", "düşmek", "hiç", "sevmek", "göz", "son",
    "kalmak", "baba", "üzerine", "yan", "yeni", "daha", "iç", "yazmak", "gitmek", "durum", "artık",
    "bulmak", "adam", "söz", "sonra", "sonuç", "ad", "çalışmak", "yüzde", "karşı", "ye"
].map(item => {
   return {"word": item, "status":"", "answer":"" }
})
